theme: jekyll-theme-slate
title: Agent Based Modelling for Spread of covid-19
description : > Agent Based Modelling for Spread of covid-19 
<br><br>
Done in collaboration with [Owen Martin](https://github.com/owingit) and Mubasshir Khan
<br><br>
#<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
